### ISSUE TITLE
Can't get any single valid code

### ISSUE THREAD

**Issue by laitlito** [zafross/NitroGiftGeneratorAndChecker#7]
Is it just me or every single code I try to generate is Invalid ?
I've been trying about 1000 codes and they all are invalid.

**Comment by BySplashGm** [comment]
because it generate a lot of random codes and check them but they are not at sure valid

**Comment by HZ-0Z3R0** [comment]
@laitlito 
Of course you won't find a valid code in 1k codes. You have to understand how many possible code combinations there are. The program generates a 16 digit long alphanumeric string to check. This means there are 26+26+10 = 62 possible combinations if there was only 1 letter. Since there's 16, and we're counting permutations, there would be 62^16 possible codes, which turns out to be 4.77e28. That's 477,000,000,000,000,000,000,000,000. 477 septillion combinations. Of course you won't get a valid code on the first 1 thousand. Even if there were 1 billion unexpired valid codes (keep in mind 250 million users use Discord so this is an overestimation), you would still have to check 477,000,000,000,000,000 codes to find a valid one. If anyone could crack a nitro code easily, Discord would be bankrupt.

**Comment by laitlito** [comment]
hmmm yeah thanks for the detailed answer bro

**Comment by ZelliDev** [comment]
@HZ-0Z3R0  Miscalculation errors, You should recalculate.

The official is 71.39E78
Well, A number with 78  zeros behind.

**Comment by TKperson** [comment]
I also did a calculation in this post: https://github.com/lnxcz/nitro-generator/issues/8#issuecomment-764987352
