### ISSUE TITLE
Rate limits

### ISSUE THREAD

**Issue by i0Z3R0** [zafross/NitroGiftGeneratorAndChecker#9]
The program doesn't check for the 5/5 rate limits, which means after the first 5 codes are checked as invalid, all codes for the next 5 minutes will show as invalid since they are actually rate limited.

**Comment by DmitrijVC** [comment]
Good idea would be to add authorization to the headers with a bot token. That would increase the amount of tries to around 250. Adding some kind of proxies could be also helpful. BUT...
Every nitro generator is useless, so there is no point in fixing this one. Snipers have more sense of being, but what's the problem with paying only 5-10$/month?

**Comment by ZelliDev** [comment]
The creator comments on the readme is nonsense. You cannot do 500 check / Mins.

The official api rate limit on discord nitro is 1 req by 1 sec.

Means only 60 / mins. That is why.

Solution 1 : Put a pause of 1 sec on each code generation
Solution 2 : Using Proxies (Slower the script due to latency connections)

PS: Even with 1500 Proxies you'll only add up to 86 Millions req / 48h (without calculating latency), on a number with 78 zeros behind. This is legitimely impossible to generate any nitros.
